### ISSUE TITLE
debug db location

### ISSUE THREAD

**Issue by DeeeeLAN** [Kuree/hgdb#47]
When attempting to connect the VS Code debugger to a simulation, what do I point to for the debug.db file? I am running xcelium and have added the following switches:
```
		-loadvpi libghdb.so:initialize_hgdb_runtime
		+DEBUG_PORT=8888
		+DEBUG_LOG=1
```
As well as adding the library to LD_LIBRARY_PATH.

Can I start the debugger before the simulation so it can stop with a breakpoint, or do I need to stop it myself and attach the debugger?

**Comment by Kuree** [comment]
You need to specify the symbol table when you attach the debugger to the simulation, using either VSCode or the console. You can see more instructions [here](https://github.com/Kuree/hgdb-debugger).

> Can I start the debugger before the simulation so it can stop with a breakpoint, or do I need to stop it myself and attach the debugger?

If the library is loaded properly, it will automatically pause the simulation when it starts. You can then attach the debugger and  set breakpoints afterwards.

**Comment by DeeeeLAN** [comment]
I guess my question is: where do I find the symbol table? Is that something that is automatically generated by the simulation compilers and somewhere in the work directory?

**Comment by Kuree** [comment]
Similar to software, the symbol table is produced by the compiler, not by the debugger. You can check out a list of supported hardware generator frameworks [here](https://github.com/Kuree/hgdb#supported-generator-frameworks). Depends on what framework it is, you might need to apply a custom patch, use a plugin, or use a post-processing program. 

If you are using an unsupported framework, please send me a link and I can take a look to see if it's possible to extract symbol table out.

**Comment by DeeeeLAN** [comment]
I see, so because we are doing custom RTL design and verification, I will need to wait for progress on hgdb-rtl then? Since I currently compile with xcelium.

**Comment by Kuree** [comment]
That is right. `hgdb-rtl` needs to rewrite the RTL so that the simulation matches with what hgdb expects. Mostly it's SSA and loop unrolling passes. Unfortunately I haven't gotten much time working on it. I will let you know once I have a semi-working prototype.

**Comment by Kuree** [comment]
I've released an experimental version of hgdb-rtl [here](https://github.com/Kuree/hgdb-rtl). Feel free to open issues there if you encounter any problems.
